/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminSugestoesRouteImport } from './routes/_authenticated/admin-sugestoes'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'
import { Route as AuthenticatedAtletasRouteImport } from './routes/_authenticated/atletas'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedCalendarioExternoRouteImport } from './routes/_authenticated/calendario-externo'
import { Route as AuthenticatedCampeonatosRouteImport } from './routes/_authenticated/campeonatos'
import { Route as AuthenticatedClubesRouteImport } from './routes/_authenticated/clubes'
import { Route as AuthenticatedConcluidosRouteImport } from './routes/_authenticated/concluidos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'
import { Route as AuthenticatedCredenciamentoRouteImport } from './routes/_authenticated/credenciamento'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmBreveRouteImport } from './routes/_authenticated/em-breve'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedFontesRouteImport } from './routes/_authenticated/fontes'
import { Route as AuthenticatedFontesConteudoRouteImport } from './routes/_authenticated/fontes-conteudo'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedIntegracaoKiwifyRouteImport } from './routes/_authenticated/integracao-kiwify'
import { Route as AuthenticatedJogosRouteImport } from './routes/_authenticated/jogos'
import { Route as AuthenticatedLixeiraRouteImport } from './routes/_authenticated/lixeira'
import { Route as AuthenticatedNovidadesRouteImport } from './routes/_authenticated/novidades'
import { Route as AuthenticatedOrcamentosRouteImport } from './routes/_authenticated/orcamentos'
import { Route as AuthenticatedPrimeirosPassosRouteImport } from './routes/_authenticated/primeiros-passos'
import { Route as AuthenticatedPrivilegiosRouteImport } from './routes/_authenticated/privilegios'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedSugestoesRouteImport } from './routes/_authenticated/sugestoes'
import { Route as ApiPublicKiwifyRouteImport } from './routes/api/public/kiwify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSugestoesRoute =
  AuthenticatedAdminSugestoesRouteImport.update({
    id: '/admin-sugestoes',
    path: '/admin-sugestoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtletasRoute = AuthenticatedAtletasRouteImport.update({
  id: '/atletas',
  path: '/atletas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioExternoRoute =
  AuthenticatedCalendarioExternoRouteImport.update({
    id: '/calendario-externo',
    path: '/calendario-externo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampeonatosRoute =
  AuthenticatedCampeonatosRouteImport.update({
    id: '/campeonatos',
    path: '/campeonatos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClubesRoute = AuthenticatedClubesRouteImport.update({
  id: '/clubes',
  path: '/clubes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConcluidosRoute = AuthenticatedConcluidosRouteImport.update({
  id: '/concluidos',
  path: '/concluidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCredenciamentoRoute =
  AuthenticatedCredenciamentoRouteImport.update({
    id: '/credenciamento',
    path: '/credenciamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmBreveRoute = AuthenticatedEmBreveRouteImport.update({
  id: '/em-breve',
  path: '/em-breve',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFontesRoute = AuthenticatedFontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFontesConteudoRoute =
  AuthenticatedFontesConteudoRouteImport.update({
    id: '/fontes-conteudo',
    path: '/fontes-conteudo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracaoKiwifyRoute =
  AuthenticatedIntegracaoKiwifyRouteImport.update({
    id: '/integracao-kiwify',
    path: '/integracao-kiwify',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJogosRoute = AuthenticatedJogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLixeiraRoute = AuthenticatedLixeiraRouteImport.update({
  id: '/lixeira',
  path: '/lixeira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovidadesRoute = AuthenticatedNovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentosRoute = AuthenticatedOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrimeirosPassosRoute =
  AuthenticatedPrimeirosPassosRouteImport.update({
    id: '/primeiros-passos',
    path: '/primeiros-passos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrivilegiosRoute =
  AuthenticatedPrivilegiosRouteImport.update({
    id: '/privilegios',
    path: '/privilegios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSugestoesRoute = AuthenticatedSugestoesRouteImport.update({
  id: '/sugestoes',
  path: '/sugestoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicKiwifyRoute = ApiPublicKiwifyRouteImport.update({
  id: '/api/public/kiwify',
  path: '/api/public/kiwify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-sugestoes': typeof AuthenticatedAdminSugestoesRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/atletas': typeof AuthenticatedAtletasRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/calendario-externo': typeof AuthenticatedCalendarioExternoRoute
  '/campeonatos': typeof AuthenticatedCampeonatosRoute
  '/clubes': typeof AuthenticatedClubesRoute
  '/concluidos': typeof AuthenticatedConcluidosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/credenciamento': typeof AuthenticatedCredenciamentoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/em-breve': typeof AuthenticatedEmBreveRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fontes': typeof AuthenticatedFontesRoute
  '/fontes-conteudo': typeof AuthenticatedFontesConteudoRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/integracao-kiwify': typeof AuthenticatedIntegracaoKiwifyRoute
  '/jogos': typeof AuthenticatedJogosRoute
  '/lixeira': typeof AuthenticatedLixeiraRoute
  '/novidades': typeof AuthenticatedNovidadesRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/primeiros-passos': typeof AuthenticatedPrimeirosPassosRoute
  '/privilegios': typeof AuthenticatedPrivilegiosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/sugestoes': typeof AuthenticatedSugestoesRoute
  '/api/public/kiwify': typeof ApiPublicKiwifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-sugestoes': typeof AuthenticatedAdminSugestoesRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/atletas': typeof AuthenticatedAtletasRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/calendario-externo': typeof AuthenticatedCalendarioExternoRoute
  '/campeonatos': typeof AuthenticatedCampeonatosRoute
  '/clubes': typeof AuthenticatedClubesRoute
  '/concluidos': typeof AuthenticatedConcluidosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/credenciamento': typeof AuthenticatedCredenciamentoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/em-breve': typeof AuthenticatedEmBreveRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fontes': typeof AuthenticatedFontesRoute
  '/fontes-conteudo': typeof AuthenticatedFontesConteudoRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/integracao-kiwify': typeof AuthenticatedIntegracaoKiwifyRoute
  '/jogos': typeof AuthenticatedJogosRoute
  '/lixeira': typeof AuthenticatedLixeiraRoute
  '/novidades': typeof AuthenticatedNovidadesRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/primeiros-passos': typeof AuthenticatedPrimeirosPassosRoute
  '/privilegios': typeof AuthenticatedPrivilegiosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/sugestoes': typeof AuthenticatedSugestoesRoute
  '/api/public/kiwify': typeof ApiPublicKiwifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-sugestoes': typeof AuthenticatedAdminSugestoesRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/atletas': typeof AuthenticatedAtletasRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/calendario-externo': typeof AuthenticatedCalendarioExternoRoute
  '/_authenticated/campeonatos': typeof AuthenticatedCampeonatosRoute
  '/_authenticated/clubes': typeof AuthenticatedClubesRoute
  '/_authenticated/concluidos': typeof AuthenticatedConcluidosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRoute
  '/_authenticated/credenciamento': typeof AuthenticatedCredenciamentoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/em-breve': typeof AuthenticatedEmBreveRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/fontes': typeof AuthenticatedFontesRoute
  '/_authenticated/fontes-conteudo': typeof AuthenticatedFontesConteudoRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/integracao-kiwify': typeof AuthenticatedIntegracaoKiwifyRoute
  '/_authenticated/jogos': typeof AuthenticatedJogosRoute
  '/_authenticated/lixeira': typeof AuthenticatedLixeiraRoute
  '/_authenticated/novidades': typeof AuthenticatedNovidadesRoute
  '/_authenticated/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/_authenticated/primeiros-passos': typeof AuthenticatedPrimeirosPassosRoute
  '/_authenticated/privilegios': typeof AuthenticatedPrivilegiosRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/sugestoes': typeof AuthenticatedSugestoesRoute
  '/api/public/kiwify': typeof ApiPublicKiwifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/obrigado'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/admin'
    | '/admin-sugestoes'
    | '/agenda'
    | '/alertas'
    | '/atletas'
    | '/calendario'
    | '/calendario-externo'
    | '/campeonatos'
    | '/clubes'
    | '/concluidos'
    | '/configuracoes'
    | '/contratos'
    | '/credenciamento'
    | '/dashboard'
    | '/em-breve'
    | '/financeiro'
    | '/fontes'
    | '/fontes-conteudo'
    | '/historico'
    | '/integracao-kiwify'
    | '/jogos'
    | '/lixeira'
    | '/novidades'
    | '/orcamentos'
    | '/primeiros-passos'
    | '/privilegios'
    | '/produtos'
    | '/relatorios'
    | '/sugestoes'
    | '/api/public/kiwify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/obrigado'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/admin'
    | '/admin-sugestoes'
    | '/agenda'
    | '/alertas'
    | '/atletas'
    | '/calendario'
    | '/calendario-externo'
    | '/campeonatos'
    | '/clubes'
    | '/concluidos'
    | '/configuracoes'
    | '/contratos'
    | '/credenciamento'
    | '/dashboard'
    | '/em-breve'
    | '/financeiro'
    | '/fontes'
    | '/fontes-conteudo'
    | '/historico'
    | '/integracao-kiwify'
    | '/jogos'
    | '/lixeira'
    | '/novidades'
    | '/orcamentos'
    | '/primeiros-passos'
    | '/privilegios'
    | '/produtos'
    | '/relatorios'
    | '/sugestoes'
    | '/api/public/kiwify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/obrigado'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/admin-sugestoes'
    | '/_authenticated/agenda'
    | '/_authenticated/alertas'
    | '/_authenticated/atletas'
    | '/_authenticated/calendario'
    | '/_authenticated/calendario-externo'
    | '/_authenticated/campeonatos'
    | '/_authenticated/clubes'
    | '/_authenticated/concluidos'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contratos'
    | '/_authenticated/credenciamento'
    | '/_authenticated/dashboard'
    | '/_authenticated/em-breve'
    | '/_authenticated/financeiro'
    | '/_authenticated/fontes'
    | '/_authenticated/fontes-conteudo'
    | '/_authenticated/historico'
    | '/_authenticated/integracao-kiwify'
    | '/_authenticated/jogos'
    | '/_authenticated/lixeira'
    | '/_authenticated/novidades'
    | '/_authenticated/orcamentos'
    | '/_authenticated/primeiros-passos'
    | '/_authenticated/privilegios'
    | '/_authenticated/produtos'
    | '/_authenticated/relatorios'
    | '/_authenticated/sugestoes'
    | '/api/public/kiwify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
  ApiPublicKiwifyRoute: typeof ApiPublicKiwifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-sugestoes': {
      id: '/_authenticated/admin-sugestoes'
      path: '/admin-sugestoes'
      fullPath: '/admin-sugestoes'
      preLoaderRoute: typeof AuthenticatedAdminSugestoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atletas': {
      id: '/_authenticated/atletas'
      path: '/atletas'
      fullPath: '/atletas'
      preLoaderRoute: typeof AuthenticatedAtletasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario-externo': {
      id: '/_authenticated/calendario-externo'
      path: '/calendario-externo'
      fullPath: '/calendario-externo'
      preLoaderRoute: typeof AuthenticatedCalendarioExternoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campeonatos': {
      id: '/_authenticated/campeonatos'
      path: '/campeonatos'
      fullPath: '/campeonatos'
      preLoaderRoute: typeof AuthenticatedCampeonatosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clubes': {
      id: '/_authenticated/clubes'
      path: '/clubes'
      fullPath: '/clubes'
      preLoaderRoute: typeof AuthenticatedClubesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concluidos': {
      id: '/_authenticated/concluidos'
      path: '/concluidos'
      fullPath: '/concluidos'
      preLoaderRoute: typeof AuthenticatedConcluidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credenciamento': {
      id: '/_authenticated/credenciamento'
      path: '/credenciamento'
      fullPath: '/credenciamento'
      preLoaderRoute: typeof AuthenticatedCredenciamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/em-breve': {
      id: '/_authenticated/em-breve'
      path: '/em-breve'
      fullPath: '/em-breve'
      preLoaderRoute: typeof AuthenticatedEmBreveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fontes': {
      id: '/_authenticated/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof AuthenticatedFontesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fontes-conteudo': {
      id: '/_authenticated/fontes-conteudo'
      path: '/fontes-conteudo'
      fullPath: '/fontes-conteudo'
      preLoaderRoute: typeof AuthenticatedFontesConteudoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracao-kiwify': {
      id: '/_authenticated/integracao-kiwify'
      path: '/integracao-kiwify'
      fullPath: '/integracao-kiwify'
      preLoaderRoute: typeof AuthenticatedIntegracaoKiwifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jogos': {
      id: '/_authenticated/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof AuthenticatedJogosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lixeira': {
      id: '/_authenticated/lixeira'
      path: '/lixeira'
      fullPath: '/lixeira'
      preLoaderRoute: typeof AuthenticatedLixeiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novidades': {
      id: '/_authenticated/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof AuthenticatedNovidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos': {
      id: '/_authenticated/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AuthenticatedOrcamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/primeiros-passos': {
      id: '/_authenticated/primeiros-passos'
      path: '/primeiros-passos'
      fullPath: '/primeiros-passos'
      preLoaderRoute: typeof AuthenticatedPrimeirosPassosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privilegios': {
      id: '/_authenticated/privilegios'
      path: '/privilegios'
      fullPath: '/privilegios'
      preLoaderRoute: typeof AuthenticatedPrivilegiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sugestoes': {
      id: '/_authenticated/sugestoes'
      path: '/sugestoes'
      fullPath: '/sugestoes'
      preLoaderRoute: typeof AuthenticatedSugestoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/kiwify': {
      id: '/api/public/kiwify'
      path: '/api/public/kiwify'
      fullPath: '/api/public/kiwify'
      preLoaderRoute: typeof ApiPublicKiwifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminSugestoesRoute: typeof AuthenticatedAdminSugestoesRoute
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedAtletasRoute: typeof AuthenticatedAtletasRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCalendarioExternoRoute: typeof AuthenticatedCalendarioExternoRoute
  AuthenticatedCampeonatosRoute: typeof AuthenticatedCampeonatosRoute
  AuthenticatedClubesRoute: typeof AuthenticatedClubesRoute
  AuthenticatedConcluidosRoute: typeof AuthenticatedConcluidosRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRoute
  AuthenticatedCredenciamentoRoute: typeof AuthenticatedCredenciamentoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmBreveRoute: typeof AuthenticatedEmBreveRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedFontesRoute: typeof AuthenticatedFontesRoute
  AuthenticatedFontesConteudoRoute: typeof AuthenticatedFontesConteudoRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedIntegracaoKiwifyRoute: typeof AuthenticatedIntegracaoKiwifyRoute
  AuthenticatedJogosRoute: typeof AuthenticatedJogosRoute
  AuthenticatedLixeiraRoute: typeof AuthenticatedLixeiraRoute
  AuthenticatedNovidadesRoute: typeof AuthenticatedNovidadesRoute
  AuthenticatedOrcamentosRoute: typeof AuthenticatedOrcamentosRoute
  AuthenticatedPrimeirosPassosRoute: typeof AuthenticatedPrimeirosPassosRoute
  AuthenticatedPrivilegiosRoute: typeof AuthenticatedPrivilegiosRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSugestoesRoute: typeof AuthenticatedSugestoesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminSugestoesRoute: AuthenticatedAdminSugestoesRoute,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedAtletasRoute: AuthenticatedAtletasRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCalendarioExternoRoute: AuthenticatedCalendarioExternoRoute,
  AuthenticatedCampeonatosRoute: AuthenticatedCampeonatosRoute,
  AuthenticatedClubesRoute: AuthenticatedClubesRoute,
  AuthenticatedConcluidosRoute: AuthenticatedConcluidosRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContratosRoute: AuthenticatedContratosRoute,
  AuthenticatedCredenciamentoRoute: AuthenticatedCredenciamentoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmBreveRoute: AuthenticatedEmBreveRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedFontesRoute: AuthenticatedFontesRoute,
  AuthenticatedFontesConteudoRoute: AuthenticatedFontesConteudoRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedIntegracaoKiwifyRoute: AuthenticatedIntegracaoKiwifyRoute,
  AuthenticatedJogosRoute: AuthenticatedJogosRoute,
  AuthenticatedLixeiraRoute: AuthenticatedLixeiraRoute,
  AuthenticatedNovidadesRoute: AuthenticatedNovidadesRoute,
  AuthenticatedOrcamentosRoute: AuthenticatedOrcamentosRoute,
  AuthenticatedPrimeirosPassosRoute: AuthenticatedPrimeirosPassosRoute,
  AuthenticatedPrivilegiosRoute: AuthenticatedPrivilegiosRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSugestoesRoute: AuthenticatedSugestoesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ObrigadoRoute: ObrigadoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
  ApiPublicKiwifyRoute: ApiPublicKiwifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
